### ISSUE TITLE
Different CSS clases are loaded when refreshing article

### ISSUE THREAD

**Issue by goodideagiver** [KowalewskiPawel/PracticaLearningBlog#25]
Enter through main view: https://practicalearning.vercel.app/
Loaded classes look like this:
![obraz](https://user-images.githubusercontent.com/55458485/149679259-c9b347b9-ca36-494e-9ccd-45c7ba9afc6a.png)
Refresh while article is loaded:
![obraz](https://user-images.githubusercontent.com/55458485/149679261-5a28fe8e-003d-42ea-8b0b-33081a951a2f.png)

**Comment by LachPawel** [comment]
Thanks, the issue was originated from the Server Side Rendering nature of the Next.js. When posts pages where loading, it didn't hydrate some of the components with correct styles. There are couple of solutions to that issue, but one of the solutions was to just use a dynamic rendering which is unfortunately opposite to what happens in case of Server Side Rendering. Nevertheless, at least styles work properly now. Solution example can be found below.

```
import dynamic from "next/dynamic";

const DynamicStyledHeader = dynamic(() => import("./StyledHeader"), {
  ssr: false,
});
```
